# This is a flow to publish to Yak
name: Yak Update

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
#     - name: get version from tag
#       env:
#         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
#       run: |
#         echo $env:GITHUB_REF
#         $env:GITHUB_REF -match "refs/tags/(?<content>.*)"
#         $RELEASE_VERSION = $matches["content"]
#         echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION" 
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet.exe for use with actions
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: nuget restore GH.MiscToolbox/GH.MiscToolbox.sln
    
    - name: Build the Solution
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: msbuild GH.MiscToolbox/GH.MiscToolbox.sln
      
    - name: Download Yak
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: curl -o GH.MiscToolbox/GH.MiscToolbox/yak.exe http://files.mcneel.com/yak/tools/latest/yak.exe
      
    - name: List yak
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: ls GH.MiscToolbox/GH.MiscToolbox
      
    - name: Build Yak
      env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: ..\..\yak.exe build
      working-directory: GH.MiscToolbox/GH.MiscToolbox/bin/Yak
      
    - name: Set Env Variable for Yak Token
      env:
        YAK_TOKEN: ${{ secrets.YAK_TOKEN }}
    
    - name: Push new version to YAK
      run: ..\..\yak.exe push
      working-directory: GH.MiscToolbox/GH.MiscToolbox/bin/Yak
    
